AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Aurora DSQL cluster setup

Parameters:
  Stage:
    Type: String
    Default: develop
    AllowedValues:
      - develop
      - main
      - release
  StackNamePrefix:
    Type: String
    Default: snngicf
    AllowedValues:
      - snngicf

Resources:
  # Aurora DSQL Cluster
  DSQLCluster:
    Type: AWS::DSQL::Cluster
    Properties:
      DeletionProtectionEnabled: false

Outputs:
  DSQLClusterIdentifier:
    Description: 'Aurora DSQL Cluster Identifier'
    Value: !Ref DSQLCluster
    Export:
      Name: !Sub ${StackNamePrefix}-db-${Stage}-DSQLClusterIdentifier
  
  DSQLClusterEndpoint:
    Description: 'Aurora DSQL Cluster Endpoint'
    Value: !GetAtt DSQLCluster.Endpoint
    Export:
      Name: !Sub ${StackNamePrefix}-db-${Stage}-DSQLClusterEndpoint