//! # SeaORM Entity Structs
//!
//! This module contains entity structs auto-generated by `sea-orm-cli`.
//! Do not edit the files in `entity/` manually.
//!
//! Generated from the database schema defined in
//! `infrastructure/liquibase_migrate/changes/`.

pub mod entity;
