openapi: "3.0.1"
info:
  title: "Inquiry API"
  version: "1.0"
servers:
- url: "https://v3bc42brtj.execute-api.ap-northeast-3.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
tags:
- name: "aws:cloudformation:stack-name"
  x-amazon-apigateway-tag-value: "snngicf-api-develop"
- name: "aws:cloudformation:logical-id"
  x-amazon-apigateway-tag-value: "HttpApi"
- name: "aws:cloudformation:stack-id"
  x-amazon-apigateway-tag-value: "arn:aws:cloudformation:ap-northeast-3:672530906129:stack/snngicf-api-develop/1190e090-4db6-11f1-95c6-06b1941746d7"
- name: "httpapi:createdBy"
  x-amazon-apigateway-tag-value: "SAM"
paths:
  /inquiries:
    get:
      responses:
        default:
          description: "Default response for GET /inquiries"
      security:
      - CognitoAuthorizer: []
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-3:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-3:672530906129:function:snngicf-api-develop-InquiryDbFunction-TlZr2R1C1Avg/invocations"
        connectionType: "INTERNET"
    post:
      responses:
        default:
          description: "Default response for POST /inquiries"
      security:
      - CognitoAuthorizer: []
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-3:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-3:672530906129:function:snngicf-api-develop-InquiryDbFunction-TlZr2R1C1Avg/invocations"
        connectionType: "INTERNET"
components:
  securitySchemes:
    CognitoAuthorizer:
      type: "oauth2"
      flows: {}
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.Authorization"
        jwtConfiguration:
          audience:
          - "10e3ku62o0cm6n1gt2h65s1u9t"
          issuer: "https://cognito-idp.ap-northeast-3.amazonaws.com/ap-northeast-3_kZfu7imK2"
        type: "jwt"
x-amazon-apigateway-cors:
  allowMethods:
  - "DELETE"
  - "GET"
  - "OPTIONS"
  - "POST"
  - "PUT"
  allowHeaders:
  - "authorization"
  - "content-type"
  maxAge: -42
  allowCredentials: false
  allowOrigins:
  - "https://ngicf-testpage.pages.dev"
x-amazon-apigateway-importexport-version: "1.0"
