openapi: "3.0.1"
info:
  title: "snngicf-api-main-http-api-main"
  version: "1.0"
servers:
- url: "https://ean35go6te.execute-api.ap-northeast-3.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
tags:
- name: "aws:cloudformation:stack-name"
  x-amazon-apigateway-tag-value: "snngicf-api-main"
- name: "aws:cloudformation:logical-id"
  x-amazon-apigateway-tag-value: "HttpApi"
- name: "aws:cloudformation:stack-id"
  x-amazon-apigateway-tag-value: "arn:aws:cloudformation:ap-northeast-3:672530906129:stack/snngicf-api-main/bcfabe30-4d14-11f1-b804-0e0ed225c2ed"
- name: "httpapi:createdBy"
  x-amazon-apigateway-tag-value: "SAM"
paths:
  /inquiries:
    get:
      responses:
        default:
          description: "Default response for GET /inquiries"
      security:
      - CognitoAuthorizer: []
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-3:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-3:672530906129:function:snngicf-api-main-InquiryDbFunction-MXgwca4dONPj/invocations"
        connectionType: "INTERNET"
    post:
      responses:
        default:
          description: "Default response for POST /inquiries"
      security:
      - CognitoAuthorizer: []
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-3:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-3:672530906129:function:snngicf-api-main-InquiryDbFunction-MXgwca4dONPj/invocations"
        connectionType: "INTERNET"
components:
  securitySchemes:
    CognitoAuthorizer:
      type: "oauth2"
      flows: {}
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.Authorization"
        jwtConfiguration:
          audience:
          - "6014kp92hbm0ejhi3dv3m06kse"
          issuer: "https://cognito-idp.ap-northeast-3.amazonaws.com/ap-northeast-3_XHm2Aia4s"
        type: "jwt"
x-amazon-apigateway-cors:
  allowMethods:
  - "DELETE"
  - "GET"
  - "OPTIONS"
  - "POST"
  - "PUT"
  allowHeaders:
  - "authorization"
  - "content-type"
  maxAge: -42
  allowCredentials: false
  allowOrigins:
  - "https://nishidemasami.github.io"
x-amazon-apigateway-importexport-version: "1.0"
